### PR TITLE
Add next-connect to extensions

### PR DESCRIPTION
**Pull request by hoangvvo**
next-connect is a method routing and middleware layer for Next.js. Powered by trouter. This allows the use of Express middleware without a custom server.

### CODE REVIEW

**Comment by timneutkens** [comment]
@hoangvvo what's the main use-case for this library? Using it in API routes?

**Comment by hoangvvo** [comment]
@timneutkens It is mainly used in API Routes, but it also works in getInitialProps (preferably, getServerProps as `req` and `res` must be present) or document middleware RFC.

**Comment by hoangvvo** [comment]
You can see the library being used in this project https://github.com/hoangvvo/nextjs-mongodb-app.

**Comment by unicodeveloper** [comment]
Please rebase @hoangvvo . Will merge once you do.

**Comment by hoangvvo** [comment]
@unicodeveloper Thanks! Recreated as #133.

**Pull request closed without merging**
