### PR TITLE
Awesome

### PR DESCRIPTION
**Pull request by ooade**
* This should make it to the list

P.S: Before merging, edit the README and point Next.js logo to your copy :)

### CODE REVIEW

**Comment by ooade** [comment]
* [My copy](https://github.com/ooade/awesome-nextjs)

**Comment by unicodeveloper** [comment]
@ooade Thank you very much. Quick question.
distance

**Comment by ooade** [comment]
@unicodeveloper I'm a bad designer. LOL :sweat_smile: 
Do you mind increasing the image width? Maybe, 200px or 250px

**Comment by ooade** [comment]
Updated it to 250px [here](https://github.com/ooade/awesome-nextjs/tree/awesome). Is it cool?
Once you approve, i'll send it over to master :+1:

**Comment by unicodeveloper** [comment]
Yeah, this is awesome. Please add it to the PR.

**Comment by ooade** [comment]
Done @unicodeveloper :smile:

**Comment by unicodeveloper** [comment]
Awesome

**Pull request merged**
